### ISSUE TITLE
Spotify app login

### ISSUE THREAD

**Issue by Bunjman** [cluclead/spotify-web#1]
The Facebook link to log into an existing account does not work in the Chrome App. Actually it does nothing at all. You can't even tell I clicked it. I also tried to set up a new account using the FB link and it too did nothing. The create an account using email button seamed to work fine. I tried to log into my existing account by email and of course it failed because my Spotify account was created using Facebook.

Thank you,
Bunjman

**Comment by cluclead** [comment]
Nice catch. I am going to push an update to fix this popup issue.

**Comment by laurierobitaille** [comment]
Did you fix it? I have the same problem|

**Comment by cluclead** [comment]
Yes, this issue is fixed. Dont you get a popup window when Facebook link is clicked?

**Comment by Bunjman** [comment]
I'm logged in! Thanks man!
