### ISSUE TITLE
Spotify doesn't play music

### ISSUE THREAD

**Issue by jay1145** [cluclead/spotify-web#3]
I have the adobe flash player up to date, logged in just fine. but when I play music, it doesn't play/load

**Comment by cluclead** [comment]
Can you provide more info like what is your OS and browser version?

**Comment by jay1145** [comment]
windows 10 and i'm using latest version of chrome

**Comment by jnflores13** [comment]
I'm on a chromebook and have the most recent version of chrome, same issue. The app opens, won't play music and keeps asking to reload

**Comment by cluclead** [comment]
Please update to version 0.2.0 which converts the packaged app to an extension. This will fix all the issues.
