### ISSUE TITLE
oops something went wrong with the playback. Reload

### ISSUE THREAD

**Issue by meeska84** [cluclead/spotify-web#4]
Nothing happens when I reload. I can't play music from the app anymore.

**Comment by nataliedee** [comment]
Ditto. I can launch the Chrome app, search for songs, and hit play, but nothing happens once you click play.

**Comment by dharrington20** [comment]
Same thing is happening for me. Now I can't listen to music in class anymore and i have tried everything that was recommended to get it to work and still nothing works.

**Comment by cluclead** [comment]
Please update to version 0.2.0 which converts the packaged app to an extension. This will fix all the issues.
